/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package radio;

/**
 *
 * A class to model Radio Objects.
 * Basic radios can have a volume and a channel.
 * This class will contain a few methods as well
 * based on the use cases generated by each section
 * @author sivagamasrinivasan
 */
public class Radio 
{

	private int volume;
	private int channel=1;
	private boolean on;
        public static final int Max_volume=10;
        private Voice driver;

	public int getVolume() {
		return this.volume;
	}

	
	public void setVolume(int voulme) {
		this.volume = voulme;
	}

	public int getChannel() 
        {
		return this.channel;
	}

	
	public void setChannel(int channel) {
		this.channel = channel;
	}

	
	 public boolean isOn()
         {
        return on;
         }
	public void setOn() 
        {
		this.on = true;
	}

   /**
     * a method to link the driver's voice
     * to this particular Radio Object.
     * @param driversVoice 
     */
        public void setDriver(Voice driver)
    {
        this.driver= driver;
    }   

    public Voice getDriver() 
    {
        return driver;
    }
    /**
     * Method under construction, used to simulate the
     * reaction to a key word when the volume is turned up,
     * it should lower itself to half the max.
     */
    public void lowervolumewhentalking()
        {
	
        if (driver.getKeyword().equals(Voice.Word))
        {
            volume=Max_volume/2;
            System.out.println("lowering volume....");
          
        }
       else
        {
            System.out.println("Driver keyword not matched:");
        }
	}
   
}
